import { Roboto } from "next/font/google";
import "./globals.css";

const font = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Mockup App",
  icons: {
    icon: "/icons/favicon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={font.variable}>
        {children}
      </body>
    </html>
  );
}
